// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.1
// source: api/git-webhook-grpc.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProjectUpdateInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Project  string `protobuf:"bytes,1,opt,name=Project,proto3" json:"Project,omitempty"`
	Branch   string `protobuf:"bytes,2,opt,name=Branch,proto3" json:"Branch,omitempty"`
	SshUrl   string `protobuf:"bytes,3,opt,name=SshUrl,proto3" json:"SshUrl,omitempty"`
	CommitId string `protobuf:"bytes,4,opt,name=CommitId,proto3" json:"CommitId,omitempty"`
}

func (x *ProjectUpdateInfo) Reset() {
	*x = ProjectUpdateInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_git_webhook_grpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectUpdateInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectUpdateInfo) ProtoMessage() {}

func (x *ProjectUpdateInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_git_webhook_grpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectUpdateInfo.ProtoReflect.Descriptor instead.
func (*ProjectUpdateInfo) Descriptor() ([]byte, []int) {
	return file_api_git_webhook_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *ProjectUpdateInfo) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *ProjectUpdateInfo) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *ProjectUpdateInfo) GetSshUrl() string {
	if x != nil {
		return x.SshUrl
	}
	return ""
}

func (x *ProjectUpdateInfo) GetCommitId() string {
	if x != nil {
		return x.CommitId
	}
	return ""
}

var File_api_git_webhook_grpc_proto protoreflect.FileDescriptor

var file_api_git_webhook_grpc_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x69, 0x74, 0x2d, 0x77, 0x65, 0x62, 0x68, 0x6f, 0x6f,
	0x6b, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d,
	0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x79, 0x0a, 0x11, 0x50, 0x72, 0x6f,
	0x6a, 0x65, 0x63, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18,
	0x0a, 0x07, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x42, 0x72, 0x61, 0x6e,
	0x63, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68,
	0x12, 0x16, 0x0a, 0x06, 0x53, 0x73, 0x68, 0x55, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x53, 0x73, 0x68, 0x55, 0x72, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x6f, 0x6d, 0x6d,
	0x69, 0x74, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x43, 0x6f, 0x6d, 0x6d,
	0x69, 0x74, 0x49, 0x64, 0x32, 0x4a, 0x0a, 0x0e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x69,
	0x64, 0x65, 0x50, 0x75, 0x73, 0x68, 0x12, 0x38, 0x0a, 0x06, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x12, 0x12, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x28, 0x01,
	0x32, 0x4a, 0x0a, 0x0e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x69, 0x64, 0x65, 0x50, 0x75,
	0x73, 0x68, 0x12, 0x38, 0x0a, 0x06, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x1a, 0x12, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x00, 0x30, 0x01, 0x42, 0x06, 0x5a, 0x04,
	0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_git_webhook_grpc_proto_rawDescOnce sync.Once
	file_api_git_webhook_grpc_proto_rawDescData = file_api_git_webhook_grpc_proto_rawDesc
)

func file_api_git_webhook_grpc_proto_rawDescGZIP() []byte {
	file_api_git_webhook_grpc_proto_rawDescOnce.Do(func() {
		file_api_git_webhook_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_git_webhook_grpc_proto_rawDescData)
	})
	return file_api_git_webhook_grpc_proto_rawDescData
}

var file_api_git_webhook_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_git_webhook_grpc_proto_goTypes = []interface{}{
	(*ProjectUpdateInfo)(nil), // 0: ProjectUpdateInfo
	(*emptypb.Empty)(nil),     // 1: google.protobuf.Empty
}
var file_api_git_webhook_grpc_proto_depIdxs = []int32{
	0, // 0: ClientSidePush.Notify:input_type -> ProjectUpdateInfo
	1, // 1: ServerSidePush.Notify:input_type -> google.protobuf.Empty
	1, // 2: ClientSidePush.Notify:output_type -> google.protobuf.Empty
	0, // 3: ServerSidePush.Notify:output_type -> ProjectUpdateInfo
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_git_webhook_grpc_proto_init() }
func file_api_git_webhook_grpc_proto_init() {
	if File_api_git_webhook_grpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_git_webhook_grpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectUpdateInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_git_webhook_grpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_git_webhook_grpc_proto_goTypes,
		DependencyIndexes: file_api_git_webhook_grpc_proto_depIdxs,
		MessageInfos:      file_api_git_webhook_grpc_proto_msgTypes,
	}.Build()
	File_api_git_webhook_grpc_proto = out.File
	file_api_git_webhook_grpc_proto_rawDesc = nil
	file_api_git_webhook_grpc_proto_goTypes = nil
	file_api_git_webhook_grpc_proto_depIdxs = nil
}
