// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.1
// source: api/git-webhook-grpc.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FilterOption int32

const (
	FilterOption_None     FilterOption = 0
	FilterOption_Added    FilterOption = 1
	FilterOption_Modified FilterOption = 2
	FilterOption_Deleted  FilterOption = 3
	FilterOption_All      FilterOption = 4
)

// Enum value maps for FilterOption.
var (
	FilterOption_name = map[int32]string{
		0: "None",
		1: "Added",
		2: "Modified",
		3: "Deleted",
		4: "All",
	}
	FilterOption_value = map[string]int32{
		"None":     0,
		"Added":    1,
		"Modified": 2,
		"Deleted":  3,
		"All":      4,
	}
)

func (x FilterOption) Enum() *FilterOption {
	p := new(FilterOption)
	*p = x
	return p
}

func (x FilterOption) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FilterOption) Descriptor() protoreflect.EnumDescriptor {
	return file_api_git_webhook_grpc_proto_enumTypes[0].Descriptor()
}

func (FilterOption) Type() protoreflect.EnumType {
	return &file_api_git_webhook_grpc_proto_enumTypes[0]
}

func (x FilterOption) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FilterOption.Descriptor instead.
func (FilterOption) EnumDescriptor() ([]byte, []int) {
	return file_api_git_webhook_grpc_proto_rawDescGZIP(), []int{0}
}

type ProjectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProjectFilter []*ProjectFilter `protobuf:"bytes,1,rep,name=projectFilter,proto3" json:"projectFilter,omitempty"`
}

func (x *ProjectRequest) Reset() {
	*x = ProjectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_git_webhook_grpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectRequest) ProtoMessage() {}

func (x *ProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_git_webhook_grpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectRequest.ProtoReflect.Descriptor instead.
func (*ProjectRequest) Descriptor() ([]byte, []int) {
	return file_api_git_webhook_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *ProjectRequest) GetProjectFilter() []*ProjectFilter {
	if x != nil {
		return x.ProjectFilter
	}
	return nil
}

type ProjectResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProjectInfo *ProjectInfo `protobuf:"bytes,1,opt,name=projectInfo,proto3" json:"projectInfo,omitempty"`
}

func (x *ProjectResponse) Reset() {
	*x = ProjectResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_git_webhook_grpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectResponse) ProtoMessage() {}

func (x *ProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_git_webhook_grpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectResponse.ProtoReflect.Descriptor instead.
func (*ProjectResponse) Descriptor() ([]byte, []int) {
	return file_api_git_webhook_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *ProjectResponse) GetProjectInfo() *ProjectInfo {
	if x != nil {
		return x.ProjectInfo
	}
	return nil
}

type ProjectFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProjectInfo  *ProjectInfo  `protobuf:"bytes,1,opt,name=projectInfo,proto3" json:"projectInfo,omitempty"`
	Excludes     []string      `protobuf:"bytes,2,rep,name=excludes,proto3" json:"excludes,omitempty"`
	FilterOption *FilterOption `protobuf:"varint,3,opt,name=filterOption,proto3,enum=FilterOption,oneof" json:"filterOption,omitempty"`
}

func (x *ProjectFilter) Reset() {
	*x = ProjectFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_git_webhook_grpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectFilter) ProtoMessage() {}

func (x *ProjectFilter) ProtoReflect() protoreflect.Message {
	mi := &file_api_git_webhook_grpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectFilter.ProtoReflect.Descriptor instead.
func (*ProjectFilter) Descriptor() ([]byte, []int) {
	return file_api_git_webhook_grpc_proto_rawDescGZIP(), []int{2}
}

func (x *ProjectFilter) GetProjectInfo() *ProjectInfo {
	if x != nil {
		return x.ProjectInfo
	}
	return nil
}

func (x *ProjectFilter) GetExcludes() []string {
	if x != nil {
		return x.Excludes
	}
	return nil
}

func (x *ProjectFilter) GetFilterOption() FilterOption {
	if x != nil && x.FilterOption != nil {
		return *x.FilterOption
	}
	return FilterOption_None
}

type ProjectInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Project  string  `protobuf:"bytes,1,opt,name=Project,proto3" json:"Project,omitempty"`
	Branch   string  `protobuf:"bytes,2,opt,name=Branch,proto3" json:"Branch,omitempty"`
	SshUrl   *string `protobuf:"bytes,3,opt,name=SshUrl,proto3,oneof" json:"SshUrl,omitempty"`
	CommitId *string `protobuf:"bytes,4,opt,name=CommitId,proto3,oneof" json:"CommitId,omitempty"`
}

func (x *ProjectInfo) Reset() {
	*x = ProjectInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_git_webhook_grpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectInfo) ProtoMessage() {}

func (x *ProjectInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_git_webhook_grpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectInfo.ProtoReflect.Descriptor instead.
func (*ProjectInfo) Descriptor() ([]byte, []int) {
	return file_api_git_webhook_grpc_proto_rawDescGZIP(), []int{3}
}

func (x *ProjectInfo) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *ProjectInfo) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *ProjectInfo) GetSshUrl() string {
	if x != nil && x.SshUrl != nil {
		return *x.SshUrl
	}
	return ""
}

func (x *ProjectInfo) GetCommitId() string {
	if x != nil && x.CommitId != nil {
		return *x.CommitId
	}
	return ""
}

var File_api_git_webhook_grpc_proto protoreflect.FileDescriptor

var file_api_git_webhook_grpc_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x69, 0x74, 0x2d, 0x77, 0x65, 0x62, 0x68, 0x6f, 0x6f,
	0x6b, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x46, 0x0a, 0x0e,
	0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x34,
	0x0a, 0x0d, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x46,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x0d, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x46, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x22, 0x41, 0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x50,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0xa4, 0x01, 0x0a, 0x0d, 0x50, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x2e, 0x0a, 0x0b, 0x70, 0x72, 0x6f,
	0x6a, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0b, 0x70, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x78, 0x63,
	0x6c, 0x75, 0x64, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x65, 0x78, 0x63,
	0x6c, 0x75, 0x64, 0x65, 0x73, 0x12, 0x36, 0x0a, 0x0c, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x46, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x0c, 0x66, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x42, 0x0f, 0x0a,
	0x0d, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x95,
	0x01, 0x0a, 0x0b, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18,
	0x0a, 0x07, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x42, 0x72, 0x61, 0x6e,
	0x63, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68,
	0x12, 0x1b, 0x0a, 0x06, 0x53, 0x73, 0x68, 0x55, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x06, 0x53, 0x73, 0x68, 0x55, 0x72, 0x6c, 0x88, 0x01, 0x01, 0x12, 0x1f, 0x0a,
	0x08, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x01, 0x52, 0x08, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x49, 0x64, 0x88, 0x01, 0x01, 0x42, 0x09,
	0x0a, 0x07, 0x5f, 0x53, 0x73, 0x68, 0x55, 0x72, 0x6c, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x43, 0x6f,
	0x6d, 0x6d, 0x69, 0x74, 0x49, 0x64, 0x2a, 0x47, 0x0a, 0x0c, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00,
	0x12, 0x09, 0x0a, 0x05, 0x41, 0x64, 0x64, 0x65, 0x64, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x4d,
	0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x64, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x64, 0x10, 0x03, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x6c, 0x6c, 0x10, 0x04, 0x32,
	0x49, 0x0a, 0x11, 0x57, 0x65, 0x62, 0x48, 0x6f, 0x6f, 0x6b, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x62, 0x65, 0x72, 0x12, 0x34, 0x0a, 0x09, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62,
	0x65, 0x12, 0x0f, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x10, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x06, 0x5a, 0x04, 0x2f, 0x61,
	0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_git_webhook_grpc_proto_rawDescOnce sync.Once
	file_api_git_webhook_grpc_proto_rawDescData = file_api_git_webhook_grpc_proto_rawDesc
)

func file_api_git_webhook_grpc_proto_rawDescGZIP() []byte {
	file_api_git_webhook_grpc_proto_rawDescOnce.Do(func() {
		file_api_git_webhook_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_git_webhook_grpc_proto_rawDescData)
	})
	return file_api_git_webhook_grpc_proto_rawDescData
}

var file_api_git_webhook_grpc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_git_webhook_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_git_webhook_grpc_proto_goTypes = []interface{}{
	(FilterOption)(0),       // 0: FilterOption
	(*ProjectRequest)(nil),  // 1: ProjectRequest
	(*ProjectResponse)(nil), // 2: ProjectResponse
	(*ProjectFilter)(nil),   // 3: ProjectFilter
	(*ProjectInfo)(nil),     // 4: ProjectInfo
}
var file_api_git_webhook_grpc_proto_depIdxs = []int32{
	3, // 0: ProjectRequest.projectFilter:type_name -> ProjectFilter
	4, // 1: ProjectResponse.projectInfo:type_name -> ProjectInfo
	4, // 2: ProjectFilter.projectInfo:type_name -> ProjectInfo
	0, // 3: ProjectFilter.filterOption:type_name -> FilterOption
	1, // 4: WebHookSubscriber.Subscribe:input_type -> ProjectRequest
	2, // 5: WebHookSubscriber.Subscribe:output_type -> ProjectResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_git_webhook_grpc_proto_init() }
func file_api_git_webhook_grpc_proto_init() {
	if File_api_git_webhook_grpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_git_webhook_grpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_git_webhook_grpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_git_webhook_grpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_git_webhook_grpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_git_webhook_grpc_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_api_git_webhook_grpc_proto_msgTypes[3].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_git_webhook_grpc_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_git_webhook_grpc_proto_goTypes,
		DependencyIndexes: file_api_git_webhook_grpc_proto_depIdxs,
		EnumInfos:         file_api_git_webhook_grpc_proto_enumTypes,
		MessageInfos:      file_api_git_webhook_grpc_proto_msgTypes,
	}.Build()
	File_api_git_webhook_grpc_proto = out.File
	file_api_git_webhook_grpc_proto_rawDesc = nil
	file_api_git_webhook_grpc_proto_goTypes = nil
	file_api_git_webhook_grpc_proto_depIdxs = nil
}
